export const LOGIN_API = '/wow-api/auth/login'
export const REGISTER_API = '/wow-api/auth/signup'
export const CHANGE_PASSWORD = '/wow-api/auth/change_password'
export const REFREST_TOKEN = '/wow-api/auth/refresh'
export const SEND_OTP = '/wow-api/auth/otp'
export const FETCH_USER_INFO = '/wow-api/auth/user-info'

export const ITEMS = '/wow-api/items'
export const CART = '/wow-api/cart-data'
export const ADD_TO_CART = '/wow-api/add-to-cart'
export const ORDER = '/wow-api/order'
export const ORDERS = '/wow-api/orders'
export const ORDER_STATUS = '/wow-api/order-status'
export const CAFE_CONFIG = '/wow-api/config'
